version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
    - dependency-name: "rails"
      update-types: ["version-update:semver-patch"]
    groups:
      prod-dependencies:
        dependency-type: "production"
        update-types:
        - minor
        - patch
      dev-dependencies:
        dependency-type: "development"
      empty-group:
        patterns:
        - "nothing-matches-this-on-purpose"
    open-pull-requests-limit: 999
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docker-semver-group:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
    groups:
      react-and-friends:
        patterns:
        - "react*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
    groups:
      all-pip:
        patterns:
        - "*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
    groups:
      all-gomod:
        patterns:
        - "*"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
    - dependency-name: "com.zaxxer:HikariCP"
    open-pull-requests-limit: 999
    groups:
      all-gradle:
        patterns:
        - "com*"
        - "org*"
        - "net*"
        exclude-patterns:
        - "net.kyori*"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 998
